erp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('panel/', include('student.urls')),
    path('panel/' , include('exam.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

]
# handler404 = 'accounts.views.error_404_view'

urlpatterns += staticfiles_urlpatterns()
if settings.DEBUG: 
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 
if settings.DEBUG: 
        urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL) 

student/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('student/update/<pk>/', views.StudentUpdateView.as_view()),
    path('student/delete/<id>/', views.student_delete),

    # path('student/section/update/<pk>/', views.SectionUpdateView.as_view()),
    # path('student/section/delete/<id>/', views.section_delete),

    path('student/session/update/<pk>/', views.SessionUpdateView.as_view()),
    path('student/session/delete/<id>/', views.session_delete),

    path('student/subject/update/<pk>/', views.SubjectUpdateView.as_view()),
    path('student/subject/delete/<id>/', views.subject_delete),

    path('student/create/', views.student_register, name='student_register'),
    path('student/show/', views.show, name='student_show'),

    path('student/subject/create/', views.coursesubject_create, name='coursesubject_create'),
    path('student/subject/list/', views.coursesubject_list, name='coursesubject_list'),

    # path('student/section/list/', views.section_list, name='section_list'),
    path('student/session/create/', views.session_create, name='session_create'),
    path('student/session/list/', views.session_list, name='session_list'),
    path('student/courses/create/', views.subject_create, name='course_create'),
    path('student/courses/list/', views.subject_list, name='course_list'),
    # path('student/class/ajax/,', views.load_Class, name='load_class_ajax')




]

student/models.py
from django.db import models
from accounts.models import *

# Create your models here.



class Courses(models.Model):
    name = models.CharField(max_length=254)
    price = models.IntegerField()

    def __str__(self):
        return self.name

class AcademicYear(models.Model):
    name = models.CharField(max_length=254)

    def __str__(self):
        return self.name

class CourseSubject(models.Model):
    course = models.ForeignKey('Courses', on_delete=models.CASCADE)
    name = models.CharField(max_length=254)

    def __str__(self):
        return self.name

class Student(models.Model):
    user = models.OneToOneField('accounts.User', on_delete=models.CASCADE)
    photo = models.ImageField(upload_to='documents/student-photo/', blank=True, null=True)
    admission_date = models.DateField()
    DOB = models.DateField()
    course = models.ForeignKey('Courses', on_delete=models.CASCADE, default=False)
    academic_year = models.ForeignKey('AcademicYear', on_delete=models.CASCADE, default=False)
    gender_choice = [
        ('1', 'Male'),
        ('2', 'Female')
    ]
    gender = models.CharField(max_length=4, choices=gender_choice)
    blood_group = models.CharField(max_length=20)
    religion = models.CharField(max_length=254)
    national_id = models.CharField(max_length=254)
    previous_school_information = models.CharField(max_length=254)
    previous_school_name = models.CharField(max_length=254)
    previous_class = models.CharField(max_length=254)
    previous_certificate = models.FileField(upload_to='documents/certificate/', blank=True, null=True)
    mother_name = models.CharField(max_length=254)
    father_name = models.CharField(max_length=254)
    health_condition_certificate = models.FileField(upload_to='documents/health', blank=True, null=True)

    def __str__(self): 
        return self.user.username



class Class(models.Model):
    name = models.CharField(max_length=254, unique=True)
    
    def __str__(self):
        return self.name
    
class Section(models.Model):
    name = models.CharField(max_length=254)
    Class = models.ForeignKey('Class', on_delete=models.SET_NULL, default=False, blank=True,null=True)

    def __str__(self):
        return self.name



class Subject(models.Model):
    name = models.CharField(max_length=254)
    Class = models.ForeignKey('Class', on_delete=models.SET_NULL, default=False, null=True)

    def __str__(self):
        return self.name

class Session(models.Model):
    name = models.CharField(max_length=254, unique=True)
    status = models.BooleanField(default=True)

    def __str__(self):
        return self.name

student/forms.py
from django import forms  
from .models import *
from accounts.models import User
from bootstrap_datepicker_plus import DatePickerInput


user_types= [
        ('1', 'Franchise'),
        ('2', 'Student'),
        ('3', 'Admin')
    ]
class SignUpForm(forms.ModelForm):
    username = forms.CharField(max_length = 30, widget = forms.TextInput(attrs={'class': 'form-control','placeholder': 'Enter your username'}))
    password = forms.CharField(widget = forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Enter your password'}))
    photo = forms.ImageField(widget = forms.ClearableFileInput(attrs={'class': 'form-control'}))
    health_condition_certificate = forms.ImageField(widget = forms.ClearableFileInput(attrs={'class': 'form-control'}))
    previous_certificate = forms.ImageField(widget = forms.ClearableFileInput(attrs={'class': 'form-control'}))


    # password1 = forms.CharField(widget = forms.PasswordInput)
# ('user', 'photo', 'admission_date', 'DOB', 'course', 'academic_year', 'gender_choice', 'gender', 'blood_group', 'religion', 'national_id', 'previous_school_information', 'previous_school_name', 'previous_class', 'previous_certificate', 'mother_name', 'father_name', 'health_condition_certificate', )
    class Meta:
        model = Student
        exclude = ['user']
        widgets = {


            'admission_date': DatePickerInput().start_of('admission_date'),
            'father_name': forms.TextInput(attrs={'class': 'form-control',  'placeholder': 'Enter Your Father Name'}),
            'mother_name': forms.TextInput(attrs={'class': 'form-control',  'placeholder': 'Enter Your Mother Name'}),
            'religion': forms.TextInput(attrs={'class': 'form-control',  'placeholder': 'Enter Your Religion'}),
            'national_id': forms.TextInput(attrs={'class': 'form-control',  'placeholder': 'Enter Your National ID'}),
            'previous_school_information': forms.TextInput(attrs={'class': 'form-control',  'placeholder': 'Enter Your Previous School Information'}),
            'previous_school_name': forms.TextInput(attrs={'class': 'form-control',  'placeholder': 'Enter Your Prevoius School Name'}),
            'previous_class': forms.TextInput(attrs={'class': 'form-control',  'placeholder': 'Enter Your Previous Class Name'}),


            'DOB': DatePickerInput().start_of('DOB'),
            'gender': forms.Select(attrs={'class': 'form-control', 'placeholder' : 'Select you gender'}),
            'blood_group': forms.TextInput(attrs={'class': 'form-control',  'placeholder': 'Enter Your Blood Group'}),
            'academic_year': forms.Select(attrs={'class': 'form-control'}),
            'course': forms.Select(attrs={'class': 'form-control'}),

            # 'Session': forms.Select(attrs={'class': 'form-control'}),
            
            
            # 'Subject' : forms.CheckboxSelectMultiple()
        }

    def clean_username(self): # check if username does not exist before
        try:
            User.objects.get(username=self.cleaned_data['username']) #get user from user model
        except User.DoesNotExist :
            return self.cleaned_data['username']

        raise forms.ValidationError("This user exist already choose an0ther username")


    def save(self): # create new user
        new_user = User.objects.create_user(username=self.cleaned_data['username'],password=self.cleaned_data['password'])
        new_user.save()
        UserProf =  super(SignUpForm,self).save(commit = False)
        UserProf.user = new_user
        UserProf.save()
        return UserProf


class CourseForm(forms.ModelForm):
    class Meta:
        model = Courses
        fields = "__all__"
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control',  'placeholder': 'Enter Course Name'}),
            'price' : forms.TextInput(attrs={'class': 'form-control',  'placeholder': 'Enter Price of the course'})
        }

class SessionForm(forms.ModelForm):
    class Meta:
        model = AcademicYear
        fields = "__all__"
        widgets = {
            'name' : forms.TextInput(attrs={'class': 'form-control',  'placeholder': 'Enter Session'}),
               
        }

class SubjectForm(forms.ModelForm):
    class Meta:
        model = CourseSubject
        fields = "__all__"
        widgets = {
            'name' : forms.TextInput(attrs={'class': 'form-control',  'placeholder': 'Enter Subject Name'}),
            'course' : forms.Select(attrs={'class': 'form-control'})   
        }

class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ['photo', 'admission_date', 'DOB', 'course', 'academic_year',  'gender', 'blood_group', 'religion', 'national_id', 'previous_school_information', 'previous_school_name', 'previous_class', 'previous_certificate', 'mother_name', 'father_name', 'health_condition_certificate']
        widgets = {


            'admission_date': DatePickerInput().start_of('admission_date'),
            'father_name': forms.TextInput(attrs={'class': 'form-control',  'placeholder': 'Enter Your Father Name'}),
            'mother_name': forms.TextInput(attrs={'class': 'form-control',  'placeholder': 'Enter Your Mother Name'}),
            'religion': forms.TextInput(attrs={'class': 'form-control',  'placeholder': 'Enter Your Religion'}),
            'national_id': forms.TextInput(attrs={'class': 'form-control',  'placeholder': 'Enter Your National ID'}),
            'previous_school_information': forms.TextInput(attrs={'class': 'form-control',  'placeholder': 'Enter Your Previous School Information'}),
            'previous_school_name': forms.TextInput(attrs={'class': 'form-control',  'placeholder': 'Enter Your Prevoius School Name'}),
            'previous_class': forms.TextInput(attrs={'class': 'form-control',  'placeholder': 'Enter Your Previous Class Name'}),


            'DOB': DatePickerInput().start_of('DOB'),
            'gender': forms.Select(attrs={'class': 'form-control', 'placeholder' : 'Select you gender'}),
            'blood_group': forms.TextInput(attrs={'class': 'form-control',  'placeholder': 'Enter Your Blood Group'}),
            'academic_year': forms.Select(attrs={'class': 'form-control'}),
            'course': forms.Select(attrs={'class': 'form-control'}),

        }

student/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect, HttpResponse
from accounts.models import *
from .forms import *
from django.views.generic.edit import UpdateView 

from django.contrib.auth.decorators import login_required

# Create your views here.

class StudentUpdateView(UpdateView): 
    # specify the model you want to use 
    model = Student
    form_class = StudentForm 
  
    # specify the fields 
    # fields = "__all__"
    template_name_suffix = '_update'
    # can specify success url 
    # url to redirect after successfully 
    # updating details 
    success_url =   "/panel/student/show/"

# @superuser_only
@login_required
def student_delete(request, id):

    arg = Student.objects.get(id=id)
    arg.delete()

    return redirect("/panel/student/show/") 





class SubjectUpdateView(UpdateView): 
    # specify the model you want to use 
    model = Courses
    form_class = CourseForm 
  
    # specify the fields 
    # fields = "__all__"
    template_name_suffix = '_update'
    # can specify success url 
    # url to redirect after successfully 
    # updating details 
    success_url =   "/panel/student/subject/list/'"

# @superuser_only
@login_required
def subject_delete(request, id):

    arg = Courses.objects.get(id=id)
    arg.delete()

    return redirect("/panel/student/subject/list/") 

class SessionUpdateView(UpdateView): 
    # specify the model you want to use 
    model = AcademicYear
    form_class = SessionForm 
  
    # specify the fields 
    # fields = "__all__"
    template_name_suffix = '_update'
    # can specify success url 
    # url to redirect after successfully 
    # updating details 
    success_url =   "/panel/student/session/list/'"

# @superuser_only
@login_required
def session_delete(request, id):

    arg = AcademicYear.objects.get(id=id)
    arg.delete()

    return redirect("/panel/student/session/list/") 

@login_required
def student_register(request):
    forms = SignUpForm()
    # form = UserForm()

    if request.method == 'POST':
        forms = SignUpForm(data=request.POST , files=request.FILES)
        if forms.is_valid():
            forms.save()
            return redirect('/panel/student/show/')
    

    return render(request, 'student/registration.html', { 'forms' : forms })
    
@login_required
def show(request):
    data = Student.objects.all()
    return render(request, 'student/show.html', {'data' : data})



@login_required
def session_create(request):
    forms = SessionForm()
    if request.method == 'POST':
        forms = SessionForm(data=request.POST)
        if forms.is_valid():
            forms.save()
            return redirect('/panel/student/session/list/')
    return render(request, 'session/form.html', {'forms' : forms})

@login_required
def session_list(request):
    data = AcademicYear.objects.all()
    return render(request, 'session/list.html', {'data' : data})

@login_required
def subject_create(request):
    forms = CourseForm()
    if request.method == 'POST':
        forms = CourseForm(data=request.POST)
        if forms.is_valid():
            forms.save()
            return redirect('/panel/student/course/list/')
    
    return render(request, 'class/course/form.html', {'forms' : forms})
@login_required
def subject_list(request):
    data = Courses.objects.all()
    return render(request, 'class/course/list.html', {'data' : data})

@login_required
def coursesubject_create(request):
    forms = SubjectForm()
    if request.method == 'POST':
        forms = SubjectForm(data=request.POST)
        if forms.is_valid():
            forms.save()
            return redirect('/panel/student/subject/list/')
    
    return render(request, 'class/section/form.html', {'forms' : forms})

@login_required
def coursesubject_list(request):
    data = CourseSubject.objects.all()
    return render(request, 'class/section/list.html', {'data' : data})

templates/student/academicyear_update.html
{% extends 'base/base.html' %}

{% block content %}
{% load crispy_forms_tags %}
  <div class="card">
    <div class="card-header">Edit AcademicYear</div>
    <div class="card-body">
      
        <div class ='container'>
          <div class="card">
            <!-- <div class="card-header">Academic Information</div> -->
            <div class="card-body">
              <form  method="POST">{% csrf_token %}
              
              <!-- {{ form.as_p }} -->
              {{ form.as_p }}
              <button type="submit" class="btn btn-primary">Update</button>
              </form>
            </div>
          </div>
          
          
        </div>

       
        

        


    </div>
  </div>
<!-- 
    <script>
      $("#id_Class").change(function () {
        var url = $("#quickForm1").attr("data-url");  // get the url of the `load_cities` view
        var ClassID = $(this).val();  // get the selected country ID from the HTML input

        $.ajax({                       // initialize an AJAX request
          url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
          data: {
            'Class': ClassID       // add the country id to the GET parameters
          },
          success: function (data) {   // `data` is the return of the `load_cities` view function
            $("#id_Section").html(data);  // replace the contents of the city input with the data that came from the server
          }
        });

      });

    </script> -->
{% endblock %}

templates/student/ajax.html
<option value="">---------</option>
{% for city in cities %}
<option value="{{ city.pk }}">{{ city.name }}</option>
{% endfor %}

templates/student/class_update.html
{% extends 'base/base.html' %}

{% block content %}
{% load crispy_forms_tags %}
  <div class="card">
    <div class="card-header">Edit Class</div>
    <div class="card-body">
      
        <div class ='container'>
          <div class="card">
            <!-- <div class="card-header">Academic Information</div> -->
            <div class="card-body">
              <form  method="POST">{% csrf_token %}
              
              <!-- {{ form.as_p }} -->
              {{ form.as_p }}
              <button type="submit" class="btn btn-primary">Update</button>
              </form>
            </div>
          </div>
          
          
        </div>

       
        

        


    </div>
  </div>
<!-- 
    <script>
      $("#id_Class").change(function () {
        var url = $("#quickForm1").attr("data-url");  // get the url of the `load_cities` view
        var ClassID = $(this).val();  // get the selected country ID from the HTML input

        $.ajax({                       // initialize an AJAX request
          url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
          data: {
            'Class': ClassID       // add the country id to the GET parameters
          },
          success: function (data) {   // `data` is the return of the `load_cities` view function
            $("#id_Section").html(data);  // replace the contents of the city input with the data that came from the server
          }
        });

      });

    </script> -->
{% endblock %}

templates/student/courses_update.html
{% extends 'base/base.html' %}

{% block content %}
{% load crispy_forms_tags %}
  <div class="card">
    <div class="card-header">Edit Student Detail</div>
    <div class="card-body">
      
        <div class ='container'>
          <div class="card">
            <!-- <div class="card-header">Academic Information</div> -->
            <div class="card-body">
              <form  method="POST">{% csrf_token %}
              
              <!-- {{ form.as_p }} -->
              {{ form.as_p }}
              <button type="submit" class="btn btn-primary">Update</button>
              </form>
            </div>
          </div>
          
          
        </div>

       
        

        


    </div>
  </div>
<!-- 
    <script>
      $("#id_Class").change(function () {
        var url = $("#quickForm1").attr("data-url");  // get the url of the `load_cities` view
        var ClassID = $(this).val();  // get the selected country ID from the HTML input

        $.ajax({                       // initialize an AJAX request
          url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
          data: {
            'Class': ClassID       // add the country id to the GET parameters
          },
          success: function (data) {   // `data` is the return of the `load_cities` view function
            $("#id_Section").html(data);  // replace the contents of the city input with the data that came from the server
          }
        });

      });

    </script> -->
{% endblock %}

templates/student/registration.html
{% extends 'base/base.html' %}

{% block content %}
{% load crispy_forms_tags %}
{% load bootstrap4 %}  
<!-- {% bootstrap_css %} -->
{% bootstrap_javascript jquery='full' %} 
  <div class="card">
    <div class="card-header">Student Register Form</div>
    <div class="card-body">
      
        <div class ='container'>
          <div class="card">
            <!-- <div class="card-header">Academic Information</div> -->
            <div class="card-body">
              <form  method="POST">{% csrf_token %}
              
              {{ forms.as_p }}
              <!-- {% forms.as_p %\} -->
              {{ forms.media }}
              <button type="submit" class="btn btn-primary">Submit</button>
              </form>
            </div>
          </div>
          
          
        </div>

       
        

        


    </div>
  </div>
<!-- 
    <script>
      $("#id_Class").change(function () {
        var url = $("#quickForm1").attr("data-url");  // get the url of the `load_cities` view
        var ClassID = $(this).val();  // get the selected country ID from the HTML input

        $.ajax({                       // initialize an AJAX request
          url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
          data: {
            'Class': ClassID       // add the country id to the GET parameters
          },
          success: function (data) {   // `data` is the return of the `load_cities` view function
            $("#id_Section").html(data);  // replace the contents of the city input with the data that came from the server
          }
        });

      });

    </script> -->
{% endblock %}

templates/student/section_update.html
{% extends 'base/base.html' %}

{% block content %}
{% load crispy_forms_tags %}
  <div class="card">
    <div class="card-header">Edit Section</div>
    <div class="card-body">
      
        <div class ='container'>
          <div class="card">
            <!-- <div class="card-header">Academic Information</div> -->
            <div class="card-body">
              <form  method="POST">{% csrf_token %}
              
              <!-- {{ form.as_p }} -->
              {{ form.as_p }}
              <button type="submit" class="btn btn-primary">Update</button>
              </form>
            </div>
          </div>
          
          
        </div>

       
        

        


    </div>
  </div>
<!-- 
    <script>
      $("#id_Class").change(function () {
        var url = $("#quickForm1").attr("data-url");  // get the url of the `load_cities` view
        var ClassID = $(this).val();  // get the selected country ID from the HTML input

        $.ajax({                       // initialize an AJAX request
          url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
          data: {
            'Class': ClassID       // add the country id to the GET parameters
          },
          success: function (data) {   // `data` is the return of the `load_cities` view function
            $("#id_Section").html(data);  // replace the contents of the city input with the data that came from the server
          }
        });

      });

    </script> -->
{% endblock %}

templates/student/show.html
{% extends 'base/base.html' %}
{% load static %}




{% block content %}
<head>

<!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> -->

</head>
	 <div class="content-wrapper">
    <!-- Content Header (Page header) -->

	<section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">User Table</h3>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table id="example" class="table table-bordered table-striped">
                  <thead>
                  <tr>
                    <th>Id</th>
                    <th>Username</th>
                    <th>Father Name</th>
                    <th>Mother Name</th>
                    <th>DOB</th>
                    <th>Gender</th>
                    <th>Course</th>
                    <th>Academic Year</th>
                    <!-- <th>Subject</th> -->
                    <th>Previous School</th>
                    <th>Previous Class</th>

                    
                    <th>Actions</th>
                  </tr>
                  </thead>
                  <tbody>
                  	{% if data %}
                  		{% for student in data %}
                  			 
  						
								<tr>
  								<td>{{ student.id }}</td>
                                  <td>{{ student.user }}</td>
                                  <td>{{ student.father_name }}</td>
                                  <td>{{ student.mother_name }}</td>
                                  <td>{{ student.DOB }}</td>
                                  <td>{{ student.gender }}</td>
                                  <td>{{ student.course }}</td>
                                  <td>{{ student.academic_year }}</td>
                                  <!-- <td>{{ student.Subject }}</td> -->
                                  <td>{{ student.previous_school_name }}</td>
                                  <td>{{ student.previous_class }}</td>

                                  

  								<td class="td-actions text-left">
                   
                      <a href="/panel/student/update/{{ student.id }}/" > 
                          <button class="btn btn-success btn-sm rounded-0" type="button" data-toggle="tooltip" data-placement="top" title="Edit" ><i class="fa fa-edit"></i></button>
                      </a>
                      <a href="/panel/student/delete/{{ student.id }}">
                        <button class="btn btn-danger btn-sm rounded-0" type="button" data-toggle="tooltip" data-placement="top" title="Delete" ><i class="fa fa-trash"></i></button>
                      </a>
                   </td>     
                </tr>
                
                {% endfor %}
                {% endif %}
                  


		               
               


                 

                  </tbody>
                  <tfoot>
                  <tr>
                    <th>Id</th>
                    <th>Username</th>
                    <th>Father Name</th>
                    <th>Mother Name</th>
                    <th>DOB</th>
                    <th>Gender</th>
                    <th>Course</th>
                    <th>Academic Year</th>
                    <!-- <th>Subject</th> -->
                    <th>Previous School</th>
                    <th>Previous Class</th>

                    
                    <th>Actions</th>
                  </tr>
                  </tfoot>
                </table> 
                 
                 </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
          <!-- /.col -->
        </div>
        <!-- /.row -->
      </div>
      <!-- /.container-fluid -->

    </section>
    <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>


{% endblock %}
{% block script%}

<script src="{% static 'admin/plugins/datatables/jquery.dataTables.min.js'%}"></script>
<script src="{% static 'admin/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js'%}"></script>
<script src="{% static 'admin/plugins/datatables-responsive/js/dataTables.responsive.min.js'%}"></script>
<script src="{% static 'admin/plugins/datatables-responsive/js/responsive.bootstrap4.min.js'%}"></script>
<!-- AdminLTE App -->

<!-- AdminLTE for demo purposes -->
<script src="{% static 'admin/dist/js/demo.js' %}"></script>
<!-- page script -->
<script>
  $(function () {
    $("#example1").DataTable({
      "responsive": true,
      "autoWidth": false,
    });
    $('#example2').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": false,
      "ordering": true,
      "info": true,
      "autoWidth": false,
      "responsive": true,
    });
  });
</script>
{% endblock %}
                                

templates/student/subject_update.html
{% extends 'base/base.html' %}

{% block content %}
{% load crispy_forms_tags %}
  <div class="card">
    <div class="card-header">Edit Subject</div>
    <div class="card-body">
      
        <div class ='container'>
          <div class="card">
            <!-- <div class="card-header">Academic Information</div> -->
            <div class="card-body">
              <form  method="POST">{% csrf_token %}
              
              <!-- {{ form.as_p }} -->
              {{ form.as_p }}
              <button type="submit" class="btn btn-primary">Update</button>
              </form>
            </div>
          </div>
          
          
        </div>

       
        

        


    </div>
  </div>
<!-- 
    <script>
      $("#id_Class").change(function () {
        var url = $("#quickForm1").attr("data-url");  // get the url of the `load_cities` view
        var ClassID = $(this).val();  // get the selected country ID from the HTML input

        $.ajax({                       // initialize an AJAX request
          url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
          data: {
            'Class': ClassID       // add the country id to the GET parameters
          },
          success: function (data) {   // `data` is the return of the `load_cities` view function
            $("#id_Section").html(data);  // replace the contents of the city input with the data that came from the server
          }
        });

      });

    </script> -->
{% endblock %}